# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
type Category @model(subscriptions: null) {
  id: ID! @primaryKey(sortKeyFields: ["name"])
  name: String!
  parent: String @index(name: "byParent", queryField: "categoriesByParent", sortKeyFields: ["name"])
  nodeID: Int! @index(name: "byNodeID", queryField: "categoriesByNode", sortKeyFields: ["name"])
  path: String!
}

type Ad @searchable @model(subscriptions: null) {
  name: String!
  description: String!
  condition: String!
  price: String
  status: String
  categoryPath: String!
  images: [Image] @hasMany
  imageCount: Int
  paidImages: Boolean
  userID: String!
  expiration: AWSDateTime!
  autoRelist: Boolean
  scheduledRelist: Int!
  # watchLists: [WatchList] @manyToMany(relationName: "AdWatchLists")
}

type Image @model(subscriptions: null) {
  url: String!
}
